<?php
return array(
	'SITE_LANG' => array('USER_NAME_EMPTY_TIP'=>'用户名不能为空！',
			'USER_PASSWD_EMPTY_TIP'=>'密码不能为空！',
			'VERIFY_CODE_EMPTY_TIP'=>'验证码不能为空！',
			'VERIFY_CODE_ERROR'=>'验证码错误！',
			'USER_PASSWD_ERROR'=>'密码错误！',
			'OLD_PASSWD_ERROR'=>'旧密码错误！',
			'LOGIN_SUCCESS_TIP'=>'登录成功！',
			'LOGIN_FAILED_TIP'=>'登录失败！',
			'USER_NAME_NOT_EXIST'=>'用户名不存在！',
			'USER_NAME_FORMAT_ERROR'=>'请检查你的用户名格式，只能使用中文，英文和数字的组合且不能超过15个字符！',
			'USER_NAME_EXISTED'=>'用户已存在，请直接登录！',
			'EMAIL_FORMAT_ERROR'=>'邮箱格式不正确！',
			'USER_PASSWD_LENGTH_ERROR'=>'请设置至少6位的密码！',
			'EMAIL_EXISTED'=>'该邮箱已注册过，请直接登录！',
			'REGISTER_SUCCESS'=>'注册成功！',
			'REGISTER_FAILED'=>'注册失败，请稍后重试！',
			'REGISTER_FORM_NOT_COMPLETE'=>'请填写完整的注册信息！',
			'LOGOUT_SUCCESS'=>'注销成功！',
			'IMAGE_UPLOAD_ERROR'=>'图片上传出错！',
			'QUERY_FAILED'=>'查询失败！',
			'MODIFY_SUCCESS'=>'修改成功！',
			'MODIFY_FAILED'=>'修改失败，请稍后重试！',
			'SAVE_FAILED'=>'保存失败，请稍后重试！',
			'USER_SIGNATURE_EMPTY_TIP'=>'签名不能为空！',
			'RESET_FAILED'=>'重置失败！',
			'RESET_SUCCESS'=>'重置成功，请重新登陆！',
			'OPERATION_FAILED'=>'操作失败！',
			'LOGIN_ALERT' => '请先登录后再操作！',
			'SITE_NAME' => 'Heysoo',
			'MSG_GET_FAILED' => '消息获取失败！',
			'REQUEST_FAILED' => '请求失败！',
			'COMMENT_SUCCESS'=>'评论成功！',
			'COMMENT_FAILED'=>'评论失败！',
			'NO_COMMENT'=>'暂无评论！',
			'COMMENT_GET_FAILED'=>'评论获取失败！',
			'COMMENT_CLOSED'=>'评论功能已关闭',
			'DELETE_SUCCESS'=>'删除成功！',
			'DELETE_FAILED'=>'删除失败！',
			'POST_SUCCESS'=>'发布成功！',
			'POST_FAILED'=>'发布失败！',
			'PIECE_CONTENT_EMPTY_TIP'=>'碎片内容不能为空！',
			'PIECE_CONTENT_LENGTH_ERROR'=>'碎片总字数不能超过255个字符！当前字数为：',
			'ESSAY_VIEW_ACCESS_DENIED'=>'你无查看此文章的权限！',
			'ESSAY_NOT_EXIST'=>'不存在此文章，或已删除！',
			'INVITE_CODE_ERROR'=>'邀请码错误或已过期！',
			'INVITE_CODE_EMPTY'=>'邀请码不能为空！',
			''=>'',
			''=>'',
			)
);